# ---- begin snakebids boilerplate ----------------------------------------------

from snakebids import (
    bids,
    filter_list,
    generate_inputs,
    get_wildcard_constraints,
)


configfile: "config/snakebids.yml"


# Workflow setup
include: "rules/setup.smk"
# Anatomical
include: "rules/anatomical.smk"


# ---- end snakebids boilerplate ------------------------------------------------
rule all:
    input:
        dtifit=expand(
            bids(
                root=work,
                suffix="b0.nii.gz",
                desc="topup",
                method="jac",
                datatype="dwi",
                **input_wildcards["dwi"],
            ),
            zip,
            **subj_zip_list,
        ),
