# ---- begin snakebids boilerplate ----------------------------------------------

from snakebids import (
    bids,
    filter_list,
    generate_inputs,
    get_wildcard_constraints,
)


configfile: "config/snakebids.yml"


# Workflow setup
include: "rules/setup.smk"
include: "rules/workflowopts.smk"
# Anatomical
include: "rules/anatomical.smk"
include: "rules/diffusion/prepdwi.smk"
include: "rules/diffusion/motioncorr.smk"
include: "rules/diffusion/topup.smk"
include: "rules/diffusion/method_grabber.smk"
include: "rules/diffusion/masking_b0_synthstrip.smk"
include: "rules/diffusion/eddy.smk"


# ---- end snakebids boilerplate ------------------------------------------------
rule all:
    input:
        dtifit=expand(
            os.path.join(
                bids(
                    root=work, suffix="eddy", datatype="dwi", **subj_wildcards
                ),
                "dwi.nii.gz",
            ),
            zip,
            **subj_zip_list,
            acquisition="notspecified",
        ),
